
server:
  port: 2023

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/repeatProject
    username: demoAccount
    password: demoaccount

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect





#      spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
