
server:
  port: 2023


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/repeatProject
    username: demoAccount
    password: demoaccount

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update



      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB


attachment:
  file-dir: uploads


#      spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
